name: {{ name }} CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13.3-alpine
        env:
          POSTGRES_DB: db_test
          POSTGRES_PASSWORD: db_test_pwd_ci
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-dev.txt

      - name: Rodar migrations
        run: ./manage.py migrate --noinput
        env:
          POSTGRES_DB: db_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: db_test_pwd_ci
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432

      - name: Tests
        run: pytest --cache-clear
        env:
          POSTGRES_DB: db_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: db_test_pwd_ci
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
